'use client';
import Link from 'next/link';
import { useState } from 'react';
import { ArrowLeft, ArrowRight, Check, WhiteFlag as Flag, Medal, EditPencil as Pencil, Plus, MoneySquare as Receipt, Archery as Target, Trash as Trash2, Group as Users } from 'iconoir-react';
import { buyerOf, forecast, isOrganized, isSharedCost, money, personMissions, personSummary, purchasingPeople, sum, withSharedCharges, type AppState, type Person, type Statement, type Transaction } from '@/lib/model';

function Face({ person }: { person: Person }) { return <span className="profile-face" style={{ color: person.color, background: person.color + '18' }}>{person.name.split(' ').filter(Boolean).slice(0, 2).map(s => s[0]).join('')}</span>; }
export function ChargeSummary({ statement, people }: { statement: Statement; people: Person[] }) {
  const fees = statement.transactions.filter(isSharedCost), ids = purchasingPeople(statement, people);
  if (!fees.length) return null;
  const unknown = statement.transactions.filter(t => !isSharedCost(t) && !buyerOf(t)).length;
  return <details className="charge-disclosure"><summary><Receipt width={19} height={19}/><span><strong>Gastos gerais · {money(sum(fees))}</strong><small>{ids.length ? `Rateio igual entre ${ids.length} compradores` : 'Indique compradores para calcular o rateio'}{unknown ? ` · provisório: ${unknown} compras sem comprador` : ''}</small></span><span className="disclosure-hint">Ver divisão</span></summary><div className="charge-details"><p>Participam os compradores indicados e as pessoas com parte positiva em compras desta fatura. Só estar cadastrado não inclui alguém. O rateio é recalculado quando as compras mudam.</p><div className="charge-items">{fees.map(t => <div key={t.id}><span>{t.merchant}</span><strong>{money(t.cents)}</strong></div>)}</div><div className="charge-shares">{ids.map(id => { const p = people.find(p => p.id === id)!; return <div key={id}><Face person={p}/><span>{p.name}</span><strong>{money(fees.reduce((n, t) => n + (t.allocations.find(a => a.personId === id)?.cents ?? 0), 0))}</strong></div>; })}</div><small>Centavos restantes são distribuídos em ordem estável, alternando entre os participantes. Nenhum valor é perdido.</small></div></details>;
}

type Props = { state: AppState; statement?: Statement; personId?: string; onAdd: () => void; onEdit: (p: Person) => void; onDelete: (p: Person) => void; onTransaction: (t: Transaction) => void; onSplit: (t: Transaction) => void };
export function PeopleWorkspace({ state, statement, personId, onAdd, onEdit, onDelete, onTransaction, onSplit }: Props) {
  const [order, setOrder] = useState('desc');
  const [historySearch, setHistorySearch] = useState('');
  const person = state.people.find(p => p.id === personId);
  const rows = state.people.map(p => ({ person: p, summary: statement ? personSummary(statement, p.id) : { purchases: 0, charges: 0, bought: 0, count: 0, total: 0 } }));
  const participants = statement ? purchasingPeople(statement, state.people) : [];
  const ranking = rows.filter(r => participants.includes(r.person.id)).sort((a, b) => order === 'desc' ? b.summary.total - a.summary.total : a.summary.total - b.summary.total);
  const max = Math.max(1, ...ranking.map(r => Math.max(0, r.summary.total)));
  const minTotal = ranking.length ? Math.min(...ranking.map(r => r.summary.total)) : 0;
  const maxTotal = ranking.length ? Math.max(...ranking.map(r => r.summary.total)) : 0;
  const pendingBuyers = statement?.transactions.filter(t => !isSharedCost(t) && !buyerOf(t)).length ?? 0;

  if (personId && !person) return <section className="panel person-missing"><h2>Pessoa não encontrada neste navegador</h2><p>Ela pode ter sido excluída ou estar em outro backup.</p><Link className="button secondary" href="/pessoas">Voltar para Pessoas</Link></section>;
  if (person) {
    const summary = statement ? personSummary(statement, person.id) : { purchases: 0, charges: 0, bought: 0, count: 0, total: 0 };
    const missions = personMissions(statement, person), completed = missions.filter(m => m.done).length;
    const ratio = person.monthlyLimitCents ? Math.max(0, summary.total / person.monthlyLimitCents * 100) : 0;
    const personal = statement?.transactions.filter(t => buyerOf(t) === person.id || t.allocations.some(a => a.personId === person.id && a.cents !== 0)) ?? [];
    const shown = personal.filter(t => `${t.merchant} ${t.note ?? ''}`.toLowerCase().includes(historySearch.toLowerCase()));
    const projection = statement ? forecast(statement, person.id).slice(0, 6) : [];
    const historical = state.statements.filter(s => s.id !== 'demo' || state.statements.length === 1).map(s => ({ statement: withSharedCharges(s, state.people), label: new Date(s.dueDate + 'T12:00:00').toLocaleDateString('pt-BR', { month: 'short', year: '2-digit' }) })).sort((a, b) => a.statement.dueDate.localeCompare(b.statement.dueDate)).slice(-6);
    const categories = new Map<string, number>();
    personal.filter(t => !isSharedCost(t)).forEach(t => categories.set(t.category, (categories.get(t.category) ?? 0) + (t.allocations.find(a => a.personId === person.id)?.cents ?? 0)));
    const categoryRows = [...categories].sort((a, b) => b[1] - a[1]);
    const maxCategory = Math.max(1, ...categoryRows.map(c => Math.max(0, c[1])));
    return <div className="people-workspace">
      <Link href="/pessoas" className="text-button"><ArrowLeft width={16} height={16}/> Todas as pessoas</Link>
      <section className="person-hero"><Face person={person}/><div><span className="eyebrow">CADERNO DE GASTOS</span><h2>{person.name}</h2><p>{summary.count} compras na divisão desta fatura</p></div><div className="person-hero-actions"><button className="button secondary" onClick={() => onEdit(person)}><Pencil width={16} height={16}/> Editar pessoa</button><button className="icon-button" aria-label={`Excluir ${person.name}`} onClick={() => onDelete(person)}><Trash2 width={18} height={18}/></button></div></section>
      {!statement && <div className="notice">Importe uma fatura para acompanhar os gastos desta pessoa.</div>}
      <div className="person-finances"><div className="personal-total"><span>Sua parte nesta fatura</span><strong>{money(summary.total)}</strong><p>Compras + gastos gerais compartilhados</p></div><div className="personal-breakdown"><div><span>Parte nas compras</span><strong>{money(summary.purchases)}</strong></div><div><span>Rateio de gastos gerais</span><strong>{money(summary.charges)}</strong></div><div><span>Compras feitas por você¹</span><strong>{money(summary.bought)}</strong></div><small>¹ Valor integral das compras em que você é o comprador, antes de dividir.</small></div></div>
      <div className="personal-planning"><section className="budget-surface"><div className="section-heading"><h3><Target width={18} height={18}/> Seu combinado</h3><button className="text-button" onClick={() => onEdit(person)}>{person.monthlyLimitCents ? 'Ajustar limite' : 'Definir limite'}</button></div>{person.monthlyLimitCents ? <><p className="budget-number">{money(summary.total)} <span>de {money(person.monthlyLimitCents)}</span></p><div className={`budget-track ${ratio > 100 ? 'over' : ''}`} role="progressbar" aria-label="Uso do limite por fatura" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.min(100, Math.round(ratio))}><span style={{ width: `${Math.min(100, ratio)}%` }}/></div><p>{ratio <= 100 ? `${money(person.monthlyLimitCents - summary.total)} até o limite.` : `${money(summary.total - person.monthlyLimitCents)} acima do combinado.`}</p><small>{statement && isOrganized(statement) ? 'Fatura conferida e organizada.' : 'Parcial: o valor pode mudar enquanto houver compras por organizar.'}</small></> : <p>Escolha um limite que faça sentido para você. Ele inclui sua parte dos encargos.</p>}</section><section className="mission-surface"><div className="mission-title"><Medal width={24} height={24}/><div><span>{completed === 3 ? 'Mês organizado' : completed > 0 ? 'No caminho' : 'Comece seu plano'}</span><small>{completed} de 3 conquistas nesta fatura</small></div></div><ul className="missions">{missions.map(m => <li key={m.title} className={m.done ? 'done' : ''}><span className="mission-check">{m.done ? <Check width={14} height={14}/> : <Flag width={13} height={13}/>}</span><span><strong>{m.title}</strong><small>{m.detail}</small></span></li>)}</ul></section></div>
      {statement && <ChargeSummary statement={statement} people={state.people}/>}
      <div className="personal-charts"><section className="panel"><div className="panel-heading"><h2>Onde ficou sua parte</h2></div><div className="category-chart">{categoryRows.length ? categoryRows.map(([category, amount]) => <div key={category}><div><span>{category}</span><strong>{money(amount)}</strong></div><div className="category-track"><span style={{ width: `${Math.max(0, amount) / maxCategory * 100}%`, background: person.color }}/></div></div>) : <p>As categorias aparecem ao atribuir compras.</p>}</div></section><section className="panel"><div className="panel-heading"><h2>Parcelas que vêm depois</h2></div><div className="personal-projection">{projection.map(p => <div key={p.label}><span>{p.label}</span><strong>{money(p.cents)}</strong></div>)}{!projection.length && <p>Sem fatura para projetar.</p>}</div><p className="chart-footnote">Estimativa da sua divisão futura, sem novas compras ou encargos futuros.</p></section></div>
      <section className="panel history-panel"><div className="panel-heading"><div><h2>Seu histórico</h2><p>Sua parte nas faturas importadas, incluindo encargos.</p></div></div>{historical.length < 2 ? <p className="history-empty">Importe mais uma fatura para comparar sua evolução. Nenhum mês é estimado aqui.</p> : <div className="history-bars">{historical.map(h => { const n = personSummary(h.statement, person.id).total; const ceiling = Math.max(1, ...historical.map(x => personSummary(x.statement, person.id).total)); return <div key={h.statement.id}><strong>{money(n)}</strong><div><span style={{ height: `${Math.max(0, n) / ceiling * 100}%`, background: person.color }}/></div><span>{h.label}</span><small>{isOrganized(h.statement) ? 'Conferida' : 'Parcial'}</small></div>; })}</div>}</section>
      <section className="panel"><div className="panel-heading"><div><h2>Compras e observações</h2><p>Compras feitas por você ou com uma parte atribuída a você.</p></div></div><label className="profile-search"><span className="sr-only">Buscar nas compras da pessoa</span><input placeholder="Buscar compra ou observação" value={historySearch} onChange={e => setHistorySearch(e.target.value)}/></label><div className="personal-transactions">{shown.map(t => <article key={t.id}><div><span className="personal-date">{t.date} · {isSharedCost(t) ? 'Gasto geral' : t.installment ? `${t.installment.current}/${t.installment.total}` : 'À vista'}</span><h3>{t.merchant}</h3><small>{isSharedCost(t) ? 'Rateio automático' : `Comprador: ${state.people.find(p => p.id === buyerOf(t))?.name ?? 'Não indicado'}`}</small><p className={t.note ? 'note-present' : 'note-empty'}>{t.note || 'Sem observação'}</p></div><div className="personal-amount"><small>Sua parte</small><strong>{money(t.allocations.find(a => a.personId === person.id)?.cents ?? 0)}</strong><small>Compra: {money(t.cents)}</small><div><button className="text-button" onClick={() => onTransaction(t)}><Pencil width={14} height={14}/> Editar</button>{!isSharedCost(t) && <button className="text-button" onClick={() => onSplit(t)}><Users width={14} height={14}/> Dividir</button>}</div></div></article>)}{!shown.length && <p className="history-empty">Nenhum lançamento encontrado para esta pessoa.</p>}</div></section>
    </div>;
  }

  return <div className="people-workspace"><div className="people-intro"><div><span className="eyebrow">PESSOAS, NÃO SÓ NÚMEROS</span><h2>Um espaço para cada comprador.</h2><p>Compras, gastos compartilhados e metas, lado a lado.</p></div><button className="button primary" onClick={onAdd}><Plus width={17} height={17}/> Adicionar pessoa</button></div>
    <section className="spend-comparison"><div className="section-heading"><div><h2>Como a fatura ficou dividida</h2><p>Parte de cada pessoa nas compras + gastos gerais.</p></div><select aria-label="Ordenar comparação de gastos" value={order} onChange={e => setOrder(e.target.value)}><option value="desc">Maior para menor gasto</option><option value="asc">Menor para maior gasto</option></select></div>{pendingBuyers > 0 && <p className="comparison-pending">Comparação parcial: {pendingBuyers} compras ainda sem comprador indicado.</p>}
      {!ranking.length ? <div className="comparison-empty"><Users width={28} height={28}/><p>Indique compradores nos lançamentos para começar a comparação.</p><Link className="text-button" href="/organizador/lancamentos">Organizar compras <ArrowRight width={16} height={16}/></Link></div> : <div className="ranking-chart">{ranking.map(r => <Link href={'/pessoas/' + encodeURIComponent(r.person.id)} key={r.person.id} className="ranking-row"><Face person={r.person}/><div className="ranking-name"><strong>{r.person.name}</strong><small>{ranking.length > 1 && r.summary.total === minTotal && minTotal !== maxTotal ? 'Menor valor' : ranking.length > 1 && r.summary.total === maxTotal && minTotal !== maxTotal ? 'Maior valor' : `${r.summary.count} compras`}</small></div><div className="ranking-track" aria-label={`${r.person.name}: compras ${money(r.summary.purchases)}, encargos ${money(r.summary.charges)}`}><span style={{ width: `${Math.max(0, r.summary.purchases) / max * 100}%`, background: r.person.color }}/><span className="charge-segment" style={{ width: `${Math.max(0, r.summary.charges) / max * 100}%` }}/></div><div className="ranking-value"><strong>{money(r.summary.total)}</strong><small>+ {money(r.summary.charges)} de gerais</small></div><ArrowRight width={16} height={16}/></Link>)}</div>}
      <div className="comparison-legend"><span><i/> Compras</span><span><i/> Gastos gerais</span><small>Valores menores não significam, por si só, melhor organização.</small></div>
    </section>
    {statement && <ChargeSummary statement={statement} people={state.people}/>}
    <section className="people-directory"><div className="section-heading"><h2>Seu grupo <span className="count-tag">{state.people.length}</span></h2><span className="helper">Abra uma pessoa para ver compras e conquistas.</span></div>{!rows.length && <div className="directory-empty"><p>Cadastre quem participa das compras. Você pode definir metas depois.</p><button className="text-button" onClick={onAdd}><Plus width={16} height={16}/> Cadastrar primeira pessoa</button></div>}{rows.map(({ person: p, summary }) => { const missions = personMissions(statement, p), done = missions.filter(m => m.done).length; return <article className="directory-row" key={p.id}><Face person={p}/><Link href={'/pessoas/' + encodeURIComponent(p.id)} className="directory-name"><strong>{p.name}</strong><small>{participants.includes(p.id) ? 'Participa desta fatura' : 'Sem compras nesta fatura'}</small></Link><div className="directory-goal"><span>{p.monthlyLimitCents ? `${money(summary.total)} de ${money(p.monthlyLimitCents)}` : 'Limite ainda não definido'}</span><small><Medal width={13} height={13}/> {done}/3 conquistas</small></div><div className="directory-actions"><button className="icon-button" onClick={() => onEdit(p)} aria-label={`Editar pessoa ${p.name}`}><Pencil width={17} height={17}/></button><Link className="text-button" href={'/pessoas/' + encodeURIComponent(p.id)}>Abrir <ArrowRight width={16} height={16}/></Link></div></article>; })}</section>
  </div>;
}
